package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, March 18, 2014 3:42:02 PM CDT
*/

public interface HelloOperations 
{
  String sayHello ();

  // This line is an operation statement
  void shutdown ();
} // interface HelloOperations
